# -*- coding: utf-8 -*-
"""task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/156L4k_644bqXbhml_YHPug9y2YmafJgI

Q1
"""

str = "python"
 
y = str.replace('o', '') 
   
 
print ("The string after removal of char: " + y)

"""Q2"""

# Python program to display all the prime numbers within an interval

l = 0
u = 10


for num in range(l, u + 1):

   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

"""Q3"""

def counter(stringg,charr):
  count = 0
  t=stringg
  for i in t:
    if i == charr:
      count = count + 1
  return count
  
# printing result 
s=counter("python",'o')
print ("The no. character: ", s)